### ISSUE TITLE
Use Vec::resize

### ISSUE THREAD

**Issue by bluss** [cybergeek94/buf_redux#1]
On line https://github.com/cybergeek94/buf_redux/blob/07bc5f90bb7ead27853f86349a6a999c7e931229/src/lib.rs#L129 you can use vec.resize instead, to grow & fill by zeros. It generates much better code.

**Comment by bluss** [comment]
Oh, since this is used in new/with_capacity, it should speed up initial creation of the buf reader pretty significantly.

**Comment by cybergeek94** [comment]
I don't like `.resize()` because it uses `.reserve()` internally, which allocates in powers of two. That's great for frequent growth but it seems too greedy in this case. Calling `.shrink_to_fit()` afterwards is even more wasteful as it requires another reallocation.

If the iterator-based zeroing isn't generating good code, we can manually lower to a call to `.set_len()` and `ptr::write_bytes()` at the cost of adding more `unsafe` blocks.

**Comment by cybergeek94** [comment]
Or is getting rid of the powers-of-two allocation totally misguided?

**Comment by bluss** [comment]
There's just a small misunderstanding: reserve only allocates if you need more space -- since you reserve enough upfront you are fine. `.extend()` will use `reserve` as well, yet it does nothing in this case for the same reason.

**Comment by cybergeek94** [comment]
See, that's the part I missed. Yeah, sounds fine to me. I'll patch it in right now.

**Comment by cybergeek94** [comment]
FIxed in `0.1.3`
